public class Constants {
    public static final String FLIGHT_STATUS_DECLINED = 'Declined';
    public static final String MAIL_SUBJECT = 'Batch was completed';
    public static final String MAIL_HTML_BODY = 'Tourists and the number of canceled flights for each of them:';
    public static final Integer FLIGHT_DELETION_PERIOD = 30;
    public static final String RESPONSE_BODY_EMPTY_NAME = 'The name must be not empty';
    public static final String RESPONSE_NOT_INTEGER_TYPE_AGE = 'The age must be a number';
    public static final String RESPONSE_BODY_DUPLICATE_RECORD = 'This tourist is already in the database';
}